Repository kaguyabot/Kaguya, pull requests merged in 2021-02, with the labels that each got.

#228 Experience service implemented.
  Kaguya/Kaguya/Database/Interfaces/IKaguyaUserRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IServerExperienceRepository.cs
  Kaguya/Kaguya/Database/Model/KaguyaUser.cs
  Kaguya/Kaguya/Database/Model/ServerExperience.cs
  Kaguya/Kaguya/Database/Repositories/KaguyaUserRepository.cs
  Kaguya/Kaguya/Database/Repositories/RoleRewardRepository.cs
  Kaguya/Kaguya/Database/Repositories/ServerExperienceRepository.cs
  Kaguya/Kaguya/Database/Repositories/UpvoteRepository.cs
  Kaguya/Kaguya/Database/Repositories/WarnConfigurationRepository.cs
  Kaguya/Kaguya/Internal/Events/EventImplementations.cs
  Kaguya/Kaguya/Internal/Events/Events.cs
  Kaguya/Kaguya/Internal/PrimitiveExtensions/MathExtensions.cs
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
  Kaguya/Kaguya/Internal/Services/FishService.cs
  Kaguya/Kaguya/Internal/Services/Recurring/AntiraidWorker.cs
  Kaguya/Kaguya/Internal/Services/Recurring/StatusRotationService.cs
  Kaguya/Kaguya/Internal/SilentSysActions.cs
  Kaguya/Kaguya/Kaguya.csproj
  Kaguya/Kaguya/Workers/DiscordWorker.cs
Labels: services:experience-global, services:experience-server, size/L

#230 Refactor Method names in Repositories
  Kaguya/Kaguya/Database/Interfaces/IAdminActionRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IFavoriteTrackRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IFishRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IGambleHistoryRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IQuoteRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IReminderRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IRepRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IRoleRewardRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IServerExperienceRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IUpvoteRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IWordFilterRepository.cs
  Kaguya/Kaguya/Database/Repositories/AdminActionRepository.cs
  Kaguya/Kaguya/Database/Repositories/FavoriteTrackRepository.cs
  Kaguya/Kaguya/Database/Repositories/FilteredWordRepository.cs
  Kaguya/Kaguya/Database/Repositories/FishRepository.cs
  Kaguya/Kaguya/Database/Repositories/GambleHistoryRepository.cs
  Kaguya/Kaguya/Database/Repositories/QuoteRepository.cs
  Kaguya/Kaguya/Database/Repositories/ReminderRepository.cs
  Kaguya/Kaguya/Database/Repositories/RepRepository.cs
  Kaguya/Kaguya/Database/Repositories/RepositoryBase.cs
  Kaguya/Kaguya/Database/Repositories/RoleRewardRepository.cs
  Kaguya/Kaguya/Database/Repositories/ServerExperienceRepository.cs
  Kaguya/Kaguya/Database/Repositories/UpvoteRepository.cs
  Kaguya/Kaguya/Discord/Commands/Administration/Filter.cs
  Kaguya/Kaguya/Discord/Commands/Administration/Mute.cs
  Kaguya/Kaguya/Discord/Commands/Configuration/AdminHistory.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Rep.cs
Labels: size/L

#233 Add blacklist bypass command attribute
  Kaguya/Kaguya/Internal/Attributes/BlacklistBypassAttribute.cs
Labels: size/S

#237 $daily command
  Kaguya/Kaguya/Discord/Commands/Exp/Daily.cs
  Kaguya/Kaguya/Discord/KaguyaBase.cs
Labels: commands:exp, size/M

#240 Users now earn 2 points whenever they earn exp
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
Labels: size/XS

#235 Text channel commands
  Kaguya/Kaguya/Discord/Commands/Administration/TextChannel.cs
Labels: commands:admin, size/L

#236 Updated $profile to look better.
  Kaguya/Kaguya/Database/Interfaces/IFishRepository.cs
  Kaguya/Kaguya/Database/Repositories/FishRepository.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Profile.cs
  Kaguya/Kaguya/Discord/CommonEmotes.cs
Labels: commands:reference, size/M

#241 Owner DM on new server join
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Events/EventImplementations.cs
  Kaguya/Kaguya/Internal/Events/Events.cs
Labels: size/M

#242 Feature/premium changes
  Kaguya/Kaguya/Discord/Commands/Administration/Role.cs
  Kaguya/Kaguya/Discord/Commands/Configuration/AdminHistory.cs
  Kaguya/Kaguya/Discord/Commands/Configuration/Antiraid.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Weekly.cs
  Kaguya/Kaguya/Discord/Commands/Games/FishGame.cs
  Kaguya/Kaguya/Discord/Commands/Reference/Help.cs
  Kaguya/Kaguya/Internal/Attributes/RestrictionAttribute.cs
  Kaguya/Kaguya/Internal/Enums/ModuleRestriction.cs
Labels: commands:premium, services:premium, size/M

#244 Feature/premium tweaks
  Kaguya/Kaguya/Discord/Commands/Reference/Invite.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Events/EventImplementations.cs
Labels: commands:premium, size/S

#257 v4 Launch bug fixes
  Kaguya/Kaguya/Database/Interfaces/IServerExperienceRepository.cs
  Kaguya/Kaguya/Database/Repositories/ServerExperienceRepository.cs
  Kaguya/Kaguya/Discord/Commands/Configuration/Antiraid.cs
  Kaguya/Kaguya/Discord/Commands/Configuration/Log.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Profile.cs
  Kaguya/Kaguya/Discord/Commands/Games/FishGame.cs
  Kaguya/Kaguya/Discord/Commands/OwnerOnly/BetaEjection.cs
  Kaguya/Kaguya/Discord/Commands/OwnerOnly/Reawaken.cs
  Kaguya/Kaguya/Discord/Commands/Reference/Changelog.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
  Kaguya/Kaguya/Kaguya.csproj
Labels: core:bug-fix, size/L

#259 Launch bug fixes
  Kaguya/Kaguya/Discord/Commands/Nsfw/Nsfw.cs
  Kaguya/Kaguya/Discord/Commands/Reference/Math.cs
  Kaguya/Kaguya/Discord/Commands/Reference/Premium.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Services/Recurring/StatusRotationService.cs
  Kaguya/Kaguya/Startup.cs
Labels: size/L

#260 Launch bug fixes
  Kaguya/Kaguya/Discord/Commands/Configuration/Antiraid.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Services/Recurring/AntiraidWorker.cs
Labels: size/M

#261 Feature/points lb
  Kaguya/Kaguya/Database/Context/KaguyaDbContext.cs
  Kaguya/Kaguya/Database/Interfaces/IKaguyaUserRepository.cs
  Kaguya/Kaguya/Database/Model/Fish.cs
  Kaguya/Kaguya/Database/Model/Giveaway.cs
  Kaguya/Kaguya/Database/Model/KaguyaStatistics.cs
  Kaguya/Kaguya/Database/Model/KaguyaUser.cs
  Kaguya/Kaguya/Database/Repositories/KaguyaStatisticsRepository.cs
  Kaguya/Kaguya/Database/Repositories/KaguyaUserRepository.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Daily.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Leaderboard.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Profile.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Weekly.cs
  Kaguya/Kaguya/Discord/Commands/Games/CrossGamble.cs
  Kaguya/Kaguya/Discord/Commands/Games/FishGame.cs
  Kaguya/Kaguya/Discord/Commands/OwnerOnly/AdjustCoins.cs
  Kaguya/Kaguya/Discord/Commands/OwnerOnly/AdjustPoints.cs
  Kaguya/Kaguya/Discord/Commands/Reference/Redeem.cs
  Kaguya/Kaguya/External/Services/TopGg/UpvoteNotifierService.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Events/EventImplementations.cs
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
  Kaguya/Kaguya/Internal/Services/FishService.cs
  Kaguya/Kaguya/Migrations/20210213063605_points_to_coins.Designer.cs
  Kaguya/Kaguya/Migrations/20210213063605_points_to_coins.cs
Labels: core:database-change, size/L

#275 Version 4.3
  Kaguya/Kaguya/Database/Interfaces/IKaguyaUserRepository.cs
  Kaguya/Kaguya/Database/Interfaces/IPremiumKeyRepository.cs
  Kaguya/Kaguya/Database/Repositories/KaguyaUserRepository.cs
  Kaguya/Kaguya/Database/Repositories/PremiumKeyRepository.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/Services/Recurring/KaguyaPremiumRoleService.cs
  Kaguya/Kaguya/Internal/Services/Recurring/TopGgStatsUpdaterService.cs
Labels: services:premium, size/L

#278 Bug/topgg
  Kaguya/Kaguya/Database/Model/KaguyaStatistics.cs
  Kaguya/Kaguya/Database/Repositories/KaguyaStatisticsRepository.cs
  Kaguya/Kaguya/Internal/Services/Recurring/TopGgStatsUpdaterService.cs
  Kaguya/Kaguya/Migrations/20210215235610_user-lastvoted.Designer.cs
  Kaguya/Kaguya/Migrations/20210215235610_user-lastvoted.cs
  Kaguya/Kaguya/Migrations/20210216065300_stats_connectedservers.Designer.cs
  Kaguya/Kaguya/Migrations/20210216065300_stats_connectedservers.cs
Labels: core:bug-fix, core:database-change, services:voting

#290 Fix/exp formula
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
  Kaguya/KaguyaTests/TestExperience.cs
Labels: size/S

#289 Fix/lingering music embeds
  Kaguya/Kaguya/Internal/Music/AudioService.cs
Labels: size/S

#288 Music Loop Command
  Kaguya/Kaguya/Discord/Commands/Music/Loop.cs
Labels: size/L

#287 Music Queue Shuffle
  Kaguya/Kaguya/Discord/Commands/Music/Shuffle.cs
  Kaguya/Kaguya/Internal/Music/MusicEmbeds.cs
Labels: size/M

#286 Fix/music fixes
  Kaguya/Kaguya/Internal/Events/EventImplementations.cs
  Kaguya/Kaguya/Internal/Events/KaguyaEvents.cs
  Kaguya/Kaguya/Internal/Music/MusicEmbeds.cs
Labels: size/M

#285 Fix/text channel
  Kaguya/Kaguya/Discord/Commands/Administration/TextChannel.cs
  Kaguya/KaguyaTests/TestTextChannelValidation.cs
Labels: size/M

#283 Fix percent to next level calc fix
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
Labels: size/XS

#282 Feature/user exp rank query speed
  Kaguya/Kaguya/Database/Context/KaguyaDbContext.cs
  Kaguya/Kaguya/Database/Repositories/KaguyaUserRepository.cs
  Kaguya/Kaguya/Database/Views/KaguyaUserExperienceRank.cs
  Kaguya/Kaguya/Kaguya.csproj
  Kaguya/Kaguya/Migrations/20210220044313_UserGlobalRankIndex.Designer.cs
  Kaguya/Kaguya/Migrations/20210220044313_UserGlobalRankIndex.cs
  Kaguya/Kaguya/Migrations/20210220051448_View_UserExperienceRank.Designer.cs
  Kaguya/Kaguya/Migrations/20210220051448_View_UserExperienceRank.cs
Labels: commands:exp, services:experience-global, size/M

#295 Added error 403 advisory to relevant role command summaries
  Kaguya/Kaguya/Discord/Commands/Administration/Role.cs
Labels: size/S

#299 Version/4.3.1
  Kaguya/Kaguya/Database/Model/KaguyaUser.cs
  Kaguya/Kaguya/Discord/Commands/Configuration/Log.cs
  Kaguya/Kaguya/Discord/Commands/Exp/Profile.cs
  Kaguya/Kaguya/Discord/Commands/Games/FishGame.cs
  Kaguya/Kaguya/Global.cs
  Kaguya/Kaguya/Internal/PrimitiveExtensions/MathExtensions.cs
  Kaguya/Kaguya/Internal/Services/ExperienceService.cs
  Kaguya/Kaguya/Internal/Services/FishService.cs
  Kaguya/Kaguya/Internal/Services/GreetingService.cs
  Kaguya/KaguyaTests/TestExperience.cs
  Kaguya/KaguyaTests/TestFish.cs
Labels: core:bug-fix, size/L
